### ISSUE TITLE
[FEAT] iOS 1차 과제

### ISSUE THREAD

**Issue by i-colours-u** [29th-WE-SOPT-iOS-Part/SongJiHun#1]
## 📌 Feature Issue

1주차 과제는 로그인, 회원가입, 확인화면 

UI 구성과 화면전환 그리고 데이터 전달입니다!

## 📝 To-do

▶️ UI 구성하기

- [x]  로그인 화면 UI 구성하기
- [x]  회원가입 화면 UI 구성하기
- [x]  확인 화면 UI 구성하기

▶️ 화면 전환하기

- [x]  로그인 화면 → 회원가입 화면 으로 push로 화면전환하기
- [x]  로그인 화면 → 확인 화면 으로 present로 화면전환하기
- [x]  회원가입 화면 → 확인 화면 으로 present로 화면전환하기

▶️ 기능 구현하기

- [x]  로그인 화면에서 적은 이름을 확인 화면에서 띄우기
- [x]  회원가입 화면에서 적은 이름을 확인 화면에서 띄우기

🔥도전과제

- [x]  로그인화면과 회원가입 화면에서 3개의 textfield값이 모두 채워지면 다음 버튼이 활성화되는 로직 구현하기
- [x]  회원가입 화면에서 비밀번호 표시를 누를 경우 비밀번호가 표시되도록 구현하기

기타 구현사항들
- [x]  키보드 띄워졌을때, 가리는 요소가 없도록 처리하기
- [x] 키보드 Toolbar에 텍스트 필드 내리는 버튼 만들어서 처리
- [x] 버튼에 대한 Haptic 관리
- [x] UI요소들에 대해서 따로 클래스 분리해서 관리하기
- [x] 터치영역 고려하기(범위가 작아서 터치하는게 힘들지 않도록)
- [x]  TextField Focus 되었을 때, 다른 Focus 되지 않은 Textfield 하고 구분되도록 border Color 처리하기
- [x] TextField Toolbar 만들어서 처리
- [x]  Module Factory 패턴으로 화면전환 처리

**Comment by seu11ee** [comment]
당신은 참 멋진 사람 .. 잘 보고 갑니다 :)

**Comment by i-colours-u** [comment]
> 당신은 참 멋진 사람 .. 잘 보고 갑니다 :)

감사합니다 🙇🏼🙇🏼
