### ISSUE TITLE
[FEAT] iOS 2차 과제

### ISSUE THREAD

**Issue by i-colours-u** [29th-WE-SOPT-iOS-Part/SongJiHun#7]
## 📝 To-do

▶️ UI 구성하기

- [ ]  로그인 화면 AutoLayout 적용하기
- [ ]  회원가입 화면 AutoLayout 적용하기
- [ ]  확인 화면 AutoLayout 적용하기
- [ ]  확인 화면에 "다른 계정으로 로그인하기" 버튼 추가하기

▶️ 화면 전환하기

- [ ]  확인 화면에 "다른 계정으로 로그인하기 버튼 추가" 누르면 처음 로그인 화면으로 돌아가기
    - 로그인 → 확인 화면으로 온 경우, 로그인 → 회원가입 → 확인 화면으로 온 경우 모두 동일하게
    버튼을 누르면 처음 로그인 화면으로 돌아가도록 구현하기
- [ ]  확인 화면에서 확인 화면 누르면 Tabbar로 연결된 화면 Present 하기

▶️ 기능 구현하기

- [ ]  Tabbar에 5개의 view controller 연결하기
- [ ]  tabbar title, image, selected image 바꾸기

▶️ 기타 구현사항

- [ ]  @propertyWrapper 활용해서 UserDefaults 관리하기
- [ ]  각 화면별로 Coordinator 패턴 적용하기
- [ ]  Router로 화면전환 제어하기
